{
    "GSD": {
        "alias": "CVE-2021-3859",
        "description": "A flaw was found in Undertow that tripped the client-side invocation timeout with certain calls made over HTTP2. This flaw allows an attacker to carry out denial of service attacks.",
        "id": "GSD-2021-3859",
        "references": [
            "https://access.redhat.com/errata/RHSA-2022:0448",
            "https://access.redhat.com/errata/RHSA-2022:0447",
            "https://access.redhat.com/errata/RHSA-2022:0415",
            "https://access.redhat.com/errata/RHSA-2022:0410",
            "https://access.redhat.com/errata/RHSA-2022:0409",
            "https://access.redhat.com/errata/RHSA-2022:0408",
            "https://access.redhat.com/errata/RHSA-2022:0407",
            "https://access.redhat.com/errata/RHSA-2022:0406",
            "https://access.redhat.com/errata/RHSA-2022:0405",
            "https://access.redhat.com/errata/RHSA-2022:0404",
            "https://access.redhat.com/errata/RHSA-2022:0401",
            "https://access.redhat.com/errata/RHSA-2022:0400",
            "https://access.redhat.com/errata/RHSA-2022:1179",
            "https://access.redhat.com/errata/RHSA-2022:5532"
        ]
    },
    "namespaces": {
        "cve.org": {
            "CVE_data_meta": {
                "ASSIGNER": "secalert@redhat.com",
                "ID": "CVE-2021-3859",
                "STATE": "PUBLIC"
            },
            "affects": {
                "vendor": {
                    "vendor_data": [
                        {
                            "product": {
                                "product_data": [
                                    {
                                        "product_name": "undertow",
                                        "version": {
                                            "version_data": [
                                                {
                                                    "version_value": "Fixed in 2.2.15.Final"
                                                }
                                            ]
                                        }
                                    }
                                ]
                            },
                            "vendor_name": "n/a"
                        }
                    ]
                }
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "eng",
                        "value": "A flaw was found in Undertow that tripped the client-side invocation timeout with certain calls made over HTTP2. This flaw allows an attacker to carry out denial of service attacks."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": [
                            {
                                "lang": "eng",
                                "value": "CWE-214 - Invocation of Process Using Visible Sensitive Information"
                            }
                        ]
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=2010378",
                        "refsource": "MISC",
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2010378"
                    },
                    {
                        "name": "https://issues.redhat.com/browse/UNDERTOW-1979",
                        "refsource": "MISC",
                        "url": "https://issues.redhat.com/browse/UNDERTOW-1979"
                    },
                    {
                        "name": "https://github.com/undertow-io/undertow/pull/1296",
                        "refsource": "MISC",
                        "url": "https://github.com/undertow-io/undertow/pull/1296"
                    },
                    {
                        "name": "https://github.com/undertow-io/undertow/commit/e43f0ada3f4da6e8579e0020cec3cb1a81e487c2",
                        "refsource": "MISC",
                        "url": "https://github.com/undertow-io/undertow/commit/e43f0ada3f4da6e8579e0020cec3cb1a81e487c2"
                    },
                    {
                        "name": "https://access.redhat.com/security/cve/CVE-2021-3859",
                        "refsource": "MISC",
                        "url": "https://access.redhat.com/security/cve/CVE-2021-3859"
                    }
                ]
            }
        },
        "nvd.nist.gov": {
            "configurations": {
                "CVE_data_version": "4.0",
                "nodes": []
            },
            "cve": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2021-3859"
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "en",
                            "value": "A flaw was found in Undertow that tripped the client-side invocation timeout with certain calls made over HTTP2. This flaw allows an attacker to carry out denial of service attacks."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": []
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://issues.redhat.com/browse/UNDERTOW-1979",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://issues.redhat.com/browse/UNDERTOW-1979"
                        },
                        {
                            "name": "https://github.com/undertow-io/undertow/commit/e43f0ada3f4da6e8579e0020cec3cb1a81e487c2",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://github.com/undertow-io/undertow/commit/e43f0ada3f4da6e8579e0020cec3cb1a81e487c2"
                        },
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=2010378",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2010378"
                        },
                        {
                            "name": "https://access.redhat.com/security/cve/CVE-2021-3859",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://access.redhat.com/security/cve/CVE-2021-3859"
                        },
                        {
                            "name": "https://github.com/undertow-io/undertow/pull/1296",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://github.com/undertow-io/undertow/pull/1296"
                        }
                    ]
                }
            },
            "impact": {},
            "lastModifiedDate": "2022-08-26T17:17Z",
            "publishedDate": "2022-08-26T16:15Z"
        }
    }
}