id: PYSEC-0000-CVE-2021-45115
details: An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and
  4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead
  in evaluating a submitted password that was artificially large in relation to the
  comparison values. In a situation where access to user registration was unrestricted,
  this provided a potential vector for a denial-of-service attack.
affected:
- package:
    name: django
    ecosystem: PyPI
    purl: pkg:pypi:django
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "2.2"
    - fixed: 2.2.26
    - introduced: "3.2"
    - fixed: 3.2.11
    - introduced: "4.0"
    - fixed: 4.0.1
references:
- type: WEB
  url: https://docs.djangoproject.com/en/4.0/releases/security/
- type: WEB
  url: https://groups.google.com/forum/#!forum/django-announce
- type: ARTICLE
  url: https://www.djangoproject.com/weblog/2022/jan/04/security-releases/
aliases:
- CVE-2021-45115
modified: "2022-01-05T00:15:00Z"
published: "2022-01-05T00:15:00Z"
