id: PYSEC-2019-108
package:
  name: numpy
  ecosystem: PyPI
summary: Vulnerability in numpy
details: '** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It
  uses the pickle Python module unsafely, which allows remote attackers to execute
  arbitrary code via a crafted serialized object, as demonstrated by a numpy.load
  call. NOTE: third parties dispute this issue because it is  a behavior that might
  have legitimate applications in (for example)  loading serialized Python object
  arrays from trusted and authenticated  sources.'
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 1.16.1
references:
- type: WEB
  url: https://github.com/numpy/numpy/issues/12759
- type: WEB
  url: https://bugzilla.suse.com/show_bug.cgi?id=1122208
- type: WEB
  url: http://www.securityfocus.com/bid/106670
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2019:3335
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2019:3704
aliases:
- CVE-2019-6446
modified: "2019-10-01T00:15:00Z"
published: "2019-01-16T05:29:00Z"
