id: PYSEC-2019-120
package:
  name: scapy
  ecosystem: PyPI
summary: Vulnerability in scapy
details: 'scapy 2.4.0 is affected by: Denial of Service. The impact is: infinite loop,
  resource consumption and program unresponsive. The component is: _RADIUSAttrPacketListField.getfield(self..).
  The attack vector is: over the network or in a pcap. both work.'
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 2.4.1
references:
- type: WEB
  url: https://github.com/secdev/scapy/pull/1409/files#diff-441eff981e466959968111fc6314fe93L1058
- type: WEB
  url: https://github.com/secdev/scapy/pull/1409
- type: WEB
  url: https://www.imperva.com/blog/scapy-sploit-python-network-tool-is-vulnerable-to-denial-of-service-dos-attack-cve-pending/
- type: WEB
  url: http://www.securityfocus.com/bid/106674
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T46XW4S5BCA3VV3JT3C5Q6LBEXSIACLN/
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/42NRPMC3NS2QVFNIXYP6WV2T3LMLLY7E/
aliases:
- CVE-2019-1010142
modified: "2020-08-24T17:37:00Z"
published: "2019-07-19T16:15:00Z"
