id: PYSEC-0000-CVE-2014-4678
package:
  name: ansible
  ecosystem: PyPI
details: 'The safe_eval function in Ansible before 1.6.4 does not properly restrict
  the code subset, which allows remote attackers to execute arbitrary code via crafted
  instructions. NOTE: this vulnerability exists because of an incomplete fix for CVE-2014-4657.'
affects:
  ranges:
  - type: GIT
    repo: https://github.com/ansible/ansible
    fixed: 5429b85b9f6c2e640074176f36ff05fd5e4d1916
  - type: ECOSYSTEM
    fixed: 1.6.4
references:
- type: WEB
  url: https://www.rapid7.com/db/vulnerabilities/freebsd-vid-2c493ac8-205e-11e5-a4a5-002590263bf5
- type: WEB
  url: https://www.rapid7.com/db/vulnerabilities/gentoo-linux-cve-2014-4678
- type: WEB
  url: https://www.openwall.com/lists/oss-security/2014/07/02/2
- type: WEB
  url: https://security-tracker.debian.org/tracker/CVE-2014-4678
- type: WEB
  url: https://www.openwall.com/lists/oss-security/2014/06/26/30
- type: WEB
  url: https://github.com/ansible/ansible/commit/5429b85b9f6c2e640074176f36ff05fd5e4d1916
- type: WEB
  url: https://groups.google.com/forum/message/raw?msg=ansible-announce/ieV1vZvcTXU/5Q93ThkY9rIJ
aliases:
- CVE-2014-4678
modified: "2020-02-25T16:12:00Z"
published: "2020-02-20T03:15:00Z"
