id: PYSEC-0000-CVE-2021-3620
details: A flaw was found in Ansible Engine's ansible-connection module, where sensitive
  information such as the Ansible user credentials is disclosed by default in the
  traceback error message. The highest threat from this vulnerability is to confidentiality.
affected:
- package:
    name: ansible
    ecosystem: PyPI
    purl: pkg:pypi/ansible
  ranges:
  - type: GIT
    repo: https://github.com/ansible/ansible
    events:
    - introduced: "0"
    - fixed: fe28767970c8ec62aabe493c46b53a5de1e5fac0
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 2.9.27
references:
- type: FIX
  url: https://github.com/ansible/ansible/commit/fe28767970c8ec62aabe493c46b53a5de1e5fac0
- type: WEB
  url: https://github.com/ansible/ansible/blob/stable-2.9/changelogs/CHANGELOG-v2.9.rst#security-fixes
- type: REPORT
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1975767
aliases:
- CVE-2021-3620
modified: "2022-03-15T12:41:00Z"
published: "2022-03-03T19:15:00Z"
