{
    "GSD": {
        "alias": "CVE-2022-30284",
        "description": "In the python-libnmap package through 0.7.2 for Python, remote command execution can occur (if used in a client application that does not validate arguments).",
        "id": "GSD-2022-30284"
    },
    "namespaces": {
        "cve.org": {
            "CVE_data_meta": {
                "ASSIGNER": "cve@mitre.org",
                "ID": "CVE-2022-30284",
                "STATE": "PUBLIC"
            },
            "affects": {
                "vendor": {
                    "vendor_data": [
                        {
                            "product": {
                                "product_data": [
                                    {
                                        "product_name": "n/a",
                                        "version": {
                                            "version_data": [
                                                {
                                                    "version_value": "n/a"
                                                }
                                            ]
                                        }
                                    }
                                ]
                            },
                            "vendor_name": "n/a"
                        }
                    ]
                }
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "eng",
                        "value": "In the python-libnmap package through 0.7.2 for Python, remote command execution can occur (if used in a client application that does not validate arguments)."
                    }
                ]
            },
            "impact": {
                "cvss": {
                    "attackComplexity": "HIGH",
                    "attackVector": "NETWORK",
                    "availabilityImpact": "HIGH",
                    "confidentialityImpact": "HIGH",
                    "integrityImpact": "HIGH",
                    "privilegesRequired": "NONE",
                    "scope": "CHANGED",
                    "userInteraction": "NONE",
                    "vectorString": "CVSS:3.1/AC:H/AV:N/A:H/C:H/I:H/PR:N/S:C/UI:N",
                    "version": "3.1"
                }
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": [
                            {
                                "lang": "eng",
                                "value": "n/a"
                            }
                        ]
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://pypi.org/project/python-libnmap/",
                        "refsource": "MISC",
                        "url": "https://pypi.org/project/python-libnmap/"
                    },
                    {
                        "name": "https://www.swascan.com/security-advisory-libnmap-2/",
                        "refsource": "MISC",
                        "url": "https://www.swascan.com/security-advisory-libnmap-2/"
                    },
                    {
                        "name": "https://github.com/savon-noir/python-libnmap/releases",
                        "refsource": "MISC",
                        "url": "https://github.com/savon-noir/python-libnmap/releases"
                    }
                ]
            }
        },
        "nvd.nist.gov": {
            "configurations": {
                "CVE_data_version": "4.0",
                "nodes": []
            },
            "cve": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2022-30284"
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "en",
                            "value": "In the python-libnmap package through 0.7.2 for Python, remote command execution can occur (if used in a client application that does not validate arguments)."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": []
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://github.com/savon-noir/python-libnmap/releases",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://github.com/savon-noir/python-libnmap/releases"
                        },
                        {
                            "name": "https://www.swascan.com/security-advisory-libnmap-2/",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://www.swascan.com/security-advisory-libnmap-2/"
                        },
                        {
                            "name": "https://pypi.org/project/python-libnmap/",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://pypi.org/project/python-libnmap/"
                        }
                    ]
                }
            },
            "impact": {},
            "lastModifiedDate": "2022-05-05T11:30Z",
            "publishedDate": "2022-05-04T22:15Z"
        }
    }
}