id: PYSEC-0000-CVE-2022-0718
details: A flaw was found in python-oslo-utils. Due to improper parsing, passwords
  with a double quote ( " ) in them cause incorrect masking in debug logs, causing
  any part of the password after the double quote to be plaintext.
affected:
- package:
    name: oslo-utils
    ecosystem: PyPI
    purl: pkg:pypi/oslo-utils
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 4.10.1
references:
- type: WEB
  url: https://security-tracker.debian.org/tracker/CVE-2022-0718
- type: REPORT
  url: https://bugzilla.redhat.com/show_bug.cgi?id=2056850
- type: WEB
  url: https://access.redhat.com/security/cve/CVE-2022-0718
- type: WEB
  url: https://bugs.launchpad.net/oslo.utils/+bug/1949623
- type: WEB
  url: https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa
aliases:
- CVE-2022-0718
modified: "2022-09-01T20:36:00Z"
published: "2022-08-29T15:15:00Z"
