{
  "schema_version": "1.4.0",
  "id": "GHSA-r8g9-w4f3-9crm",
  "modified": "2022-05-24T16:55:55Z",
  "published": "2022-05-24T16:55:55Z",
  "aliases": [
    "CVE-2019-16226"
  ],
  "details": "An issue was discovered in py-lmdb 0.97. mdb_node_del does not validate a memmove in the case of an unexpected node->mn_hi, leading to an invalid write operation.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-16226"
    },
    {
      "type": "WEB",
      "url": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20memory%20corruption%20vuln"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2019-09-11T15:15:00Z"
  }
}