id: PYSEC-0000-CVE-2022-40899
details: An issue discovered in Python Charmers Future 0.18.2 and earlier allows remote
  attackers to cause a denial of service via crafted Set-Cookie header from malicious
  web server.
affected:
- package:
    name: future
    ecosystem: PyPI
    purl: pkg:pypi/future
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 0.18.3
references:
- type: PACKAGE
  url: https://pypi.org/project/future/
- type: EVIDENCE
  url: https://github.com/python/cpython/pull/17157
- type: FIX
  url: https://github.com/python/cpython/pull/17157
- type: WEB
  url: https://github.com/python/cpython/pull/17157
- type: WEB
  url: https://github.com/PythonCharmers/python-future/blob/master/src/future/backports/http/cookiejar.py#L215
- type: EVIDENCE
  url: https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/
- type: ADVISORY
  url: https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/
- type: WEB
  url: https://github.com/PythonCharmers/python-future/pull/610
aliases:
- CVE-2022-40899
modified: "2023-01-13T22:15:00Z"
published: "2022-12-23T00:15:00Z"
